name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Command to build your Next.js app
          build: npm run build
          # Command to start your Next.js app
          start: npm run start
          # Command to run Cypress tests
          command: npm run cypress:run
          # URL to wait for before starting tests
          wait-on: 'http://localhost:3000'
          # How long to wait for the app to start (optional)
          wait-on-timeout: 120 # in seconds
        env:
          # Pass secrets to your application/tests if needed for S3 uploads
          # These must be configured in your GitHub repository secrets
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          # If your Firebase setup required client-side API keys for tests (though yours is hardcoded):
          # NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          # etc.

      # Optional: Upload test artifacts (screenshots, videos)
      # - name: Upload Cypress artifacts
      #   uses: actions/upload-artifact@v4
      #   if: failure() # Only upload on failure, or use always()
      #   with:
      #     name: cypress-artifacts
      #     path: |
      #       cypress/screenshots
      #       cypress/videos